name: "Ma serie de test"
on:
  push:
    branches:
      - develop
jobs:
  toto-job:
    runs-on: ubuntu-latest
    steps:
      - name: Execute script install
        run: ./.github/scripts/install.sh
        shell: bash 