name: "Ma serie de test"
on:
  push:

jobs:
  toto-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list file directory
        run: ls
      - name: change permission install.sh
        run: chmod 711 ./.github/scripts/install.sh
      - name: Execute script install
        run: ./.github/scripts/install.sh
        shell: bash 