name: "Ma serie de test"
on:
  push:

jobs:
  toto-job:
    runs-on: ubuntu-latest
    steps:
      - name: list file directory
        run: ls
      - name: Execute script install
        run: ./.github/scripts/install.sh
        shell: bash 