name: "Test de mon app"
on:
  push:

jobs: 
  # install: 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Je fais l'install"

  # build:
  #   needs: install
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Je fais le build"

  # test-unitaire:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node: [6, 8, 10]
  #   steps:
  #     - uses: actions/setup-node@v2
  #       with: 
  #         node-version: ${{ matrix.node }}
  #     - run: echo "Je test sur la version de node ${{ matrix.node }}"

  test-fonctionel:
    # needs: test-unitaire
    runs-on: ubuntu-latest
    strategy:
      matrix:
        appversion: [1.0.0, 2.0.0, 3.0.1]
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: refs/tags/${{ matrix.appversion}}
      - run: ls
